# Generated by Django 4.1.7 on 2023-06-24 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ceo", "0001_initial"),
        ("mentor", "0003_exam_grade"),
        ("student", "0002_answer"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnswerExam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exam_file",
                    models.FileField(
                        blank=True, max_length=200, null=True, upload_to=""
                    ),
                ),
                ("caption", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_exam",
                        to="ceo.course",
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_aswer",
                        to="mentor.exam",
                    ),
                ),
                (
                    "mentor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentor_answer_exam",
                        to="mentor.mentor",
                    ),
                ),
                (
                    "student",
                    models.ManyToManyField(
                        related_name="student_exam", to="student.student"
                    ),
                ),
            ],
        ),
    ]
